version: "3"
services:
  app:
    image: "node:alpine"
    container_name: chess_bot
    environment:
      APP_TOKEN: "YOUR DISCORD BOT TOKEN GOES HERE"
      APP_OWNER: "YOUR DISCORD ID GOES HERE"
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    ports:
      - "8080:8080"
    command: sh run.sh